/*
 * AUTO-GENERATED CONFIGURATION FILE
 * Generated from config.yaml
 * DO NOT EDIT THIS FILE DIRECTLY - Edit config.yaml instead
 */

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
const char* WIFI_SSID = "SLT_FIBRE";
const char* WIFI_PASSWORD = "abcd1234";

// Motor Configuration
const int MOTOR_DIRECTION_CORRECTION[4] = {-1, 1, 1, 1};
const int MOTOR_MAX_SPEED = 255;
const int MOTOR_PWM_FREQUENCY = 1000;
const int MOTOR_PWM_RESOLUTION = 8;
const int MOTOR2_STARTUP_DELAY = 50;

// Motor Pin Configuration
const int MOTOR_PINS[4][2] = {
    {16, 17},  // FRONT_RIGHT_MOTOR
    {18, 19},   // BACK_RIGHT_MOTOR
    {27, 26},   // FRONT_LEFT_MOTOR
    {25, 33}     // BACK_LEFT_MOTOR
};

// System Configuration
const bool ENABLE_DEBUG_OUTPUT = true;

#endif // CONFIG_H
